/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package AprendiendoMatematicas;

/**
 *
 * @author ONYXz
 */
public class Pruebas extends javax.swing.JFrame {
    String cadena,cadena1,cadena2;
    /**
     * Creates new form Pruebas
     */
    public Pruebas() {
        initComponents();
        
//<html>  <style type='text/css'> .estilo1{font-family:Times New Roman;font-style:italic;font-weight:bold; font-size:14px;color:rgb(51, 0, 153);} .estilo2{font-family:Arial;font-weight:bold; font-size:10px;color:rgb(153, 102, 0);}</style> <span class='estilo1'>Evangelión</span><br/>  <span class='estilo2'>Rei Ayanami</span></html>
      
        cadena="<html>  <style type='text/css'>"
                + ".estilo1{font-family:Times New Roman;font-style:italic;font-weight:bold; font-size:14px;color:rgb(51, 0, 153);}"
                + ".estilo2{font-family:Arial;font-weight:bold; font-size:10px;color:rgb(153, 102, 0);}</style>"
                + "<span class='estilo1'>Evangelión</span><br/>  <span class='estilo2'>Rei Ayanami</span></html>";
        cadena1="<html>  <style type='text/css'> "
                + ".estilo1{font-family:Times New Roman;font-style:italic;font-weight:bold; font-size:24px;color:rgb(255, 50, 0);}"
                + ".estilo2{font-family:Arial;font-weight:bold; font-size:12px;color:rgb(51, 0, 255);}  </style> "
                + "<span class='estilo1'>J2Button</span><br/>  <span class='estilo2'>by Mouse</span> </html> ";
        
        uno.setText(cadena);
        tres.setText(cadena1);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uno = new javax.swing.JButton();
        dos = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        cinco = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        uno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AprendiendoMatematicas/reim.png"))); // NOI18N
        uno.setText("jButton1");

        dos.setText("jButton1");

        tres.setText("jButton1");

        cuatro.setText("<html>  <style type='text/css'>\"                 + \".estilo1{font-family:Times New Roman;font-style:italic;font-weight:bold; font-size:14px;color:rgb(51, 0, 153);}\"                 + \".estilo2{font-family:Arial;font-weight:bold; font-size:10px;color:rgb(153, 102, 0);}</style>\"                 + \"<span class='estilo1'>Evangelión</span><br/>  <span class='estilo2'>Rei Ayanami</span></html>");

        cinco.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cinco, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(dos, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(uno))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(uno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tres, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cuatro, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cinco, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(dos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pruebas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pruebas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cinco;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton dos;
    private javax.swing.JButton tres;
    private javax.swing.JButton uno;
    // End of variables declaration//GEN-END:variables
}
