package Numeros;
import AprendiendoMatematicas.ClaseEdSoft;
import AprendiendoMatematicas.MDIAplicacion;
import java.applet.AudioClip;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JInternalFrame;

public final class LaSuma1 extends javax.swing.JInternalFrame {
    boolean bandera=false;
    int rango,num1,num2,num3,suma,limite,contador,totalmensajes=5;
    int pCorrecto=0,pError=0,pTotal=0,pPuntos;
    //--------------------------------------------------------------------------
    ClaseEdSoft clase=new ClaseEdSoft();
    String[] mensajeCorrecto = {"Muy bien!", "Sigue así.", "Correcto!","Acertaste!","Bien!"};
    String[] mensajeIncorrecto = {"Intentalo de nuevo.", "Ops... ERROR","Oh, no!","Puedes lograrlo!","Sigue intentando"};
    
    public LaSuma1() {
        initComponents();
        rango=5;
        suma(rango);
        mensaje.setText("");
        respuesta.requestFocus();
    }
    public void centrar(JInternalFrame frmPrincipal){
        frmPrincipal.setOpaque(false);
        frmPrincipal.setVisible(true);
        int x = (MDIAplicacion.desktopPane.getWidth() / 2) - frmPrincipal.getWidth() / 2; 
        if (frmPrincipal.isShowing()) {
            frmPrincipal.setLocation(x, 0);
        } else {
            MDIAplicacion.desktopPane.add(frmPrincipal);
            frmPrincipal.setLocation(x, 0);  
            frmPrincipal.show();
        }
      frmPrincipal.moveToFront();  
    }
    public void suma(int rango){
        contador=0;
        num1=1+(int)(Math.random()*rango);
        num2=(int)(Math.random()*rango);
        respuesta.setText("");
        respuesta.requestFocus();
        suma=num1+num2;
        if(suma>9){limite=1;}
        else{limite=0;}
        //----------------------------------------------------------------------
        num3=1+(int)(Math.random()*2);
        if(num1<=10 && num2<=10){
            if(num1==0){
                cambiarIcono(imagen2,"/Numeros/iconos/imagen0.png");                
            }else{
                cambiarIcono(imagen2,"/Numeros/iconos/imagen"+num3+"-"+num1+".png");
            }
            if(num2==0){
                cambiarIcono(imagen1,"/Numeros/iconos/imagen0.png");                
            }else{
                cambiarIcono(imagen1,"/Numeros/iconos/imagen"+num3+"-"+num2+".png");
            }             
        }else{
            cambiarIcono(imagen2,"/Numeros/iconos/imagen0.png");
            cambiarIcono(imagen1,"/Numeros/iconos/imagen0.png");
        }        
    }
    public void conf_text_buton(JButton boton,int x, int y, int z,int tamanio){
        boton.setForeground(new Color(x, y, z));
        Font controlFont = new Font("Tahoma", Font.TYPE1_FONT, tamanio);
        boton.setFont(controlFont);
        clase.sonido("/Sonidos/water1.wav");
    }
    public void cambiarIcono(JButton boton,String icono){
        boton.setIcon(new ImageIcon(getClass().getResource(icono)));
    }
    public void sonido(String cadena){
        AudioClip sonido=java.applet.Applet.newAudioClip(getClass().getResource(cadena));
        sonido.play();
    }
    public String mensajeColor(String estilo, String mensaje){
        String men="<html><style type='text/css'>"
                + ".estilo1{font-family:Times New Roman;font-style:normal;font-weight:bold; font-size:18px;color:rgb(161, 1, 3);text-align:center}   "
                + ".estilo2{font-family:verdana;font-weight:bold; font-size:18px;color:rgb(12, 149, 1);text-align:center}</style>  "
                + "<span class='"+estilo+"'>"+mensaje+"</div></body></html>";
        return men;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        suma1 = new javax.swing.JTextField();
        suma2 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        imagen1 = new javax.swing.JButton();
        signo1 = new javax.swing.JButton();
        imagen2 = new javax.swing.JButton();
        signo = new javax.swing.JButton();
        respuesta = new javax.swing.JTextField();
        mensaje = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        anterior2 = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();

        setClosable(true);
        setTitle("Aprende los Numeros con EdSoftMate");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Numeros/numeros.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Chicken Butt", 0, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("La Suma");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "La Suma", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Vijaya", 0, 20), new java.awt.Color(102, 0, 0))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jLabel2.setText("La suma es juntar dos o más números (o cosas) para tener un nuevo total.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Aquí sumamos 1 bola");
        jLabel4.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("y 1 bola");
        jLabel6.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText(" para hacer 2 bolas:");
        jLabel5.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Usando números es:");
        jLabel7.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Y en palabras es:");
        jLabel8.setToolTipText("");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Numeros/iconos/logo1.png"))); // NOI18N

        suma1.setEditable(false);
        suma1.setBackground(new java.awt.Color(224, 223, 223));
        suma1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        suma1.setForeground(new java.awt.Color(11, 141, 54));
        suma1.setOpaque(false);
        suma1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                suma1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suma1MouseExited(evt);
            }
        });

        suma2.setEditable(false);
        suma2.setBackground(new java.awt.Color(224, 223, 223));
        suma2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        suma2.setForeground(new java.awt.Color(11, 141, 54));
        suma2.setOpaque(false);
        suma2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                suma2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                suma2MouseExited(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jPanel1Layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(suma1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 152, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(suma2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 313, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(jLabel4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel6)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel5)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(suma1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(suma2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Prueba Tú: Cuenta las frutas y escribe la respuesta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Vijaya", 0, 20), new java.awt.Color(153, 0, 0))); // NOI18N

        imagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Colores/quecolorsigue/imagen.png"))); // NOI18N
        imagen1.setToolTipText("¿Qué color es?");
        imagen1.setBorder(null);
        imagen1.setBorderPainted(false);
        imagen1.setContentAreaFilled(false);
        imagen1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imagen1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imagen1.setIconTextGap(-3);
        imagen1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        imagen1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        imagen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagen1ActionPerformed(evt);
            }
        });

        signo1.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        signo1.setText("+");
        signo1.setToolTipText("");
        signo1.setBorderPainted(false);
        signo1.setContentAreaFilled(false);

        imagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Colores/quecolorsigue/imagen.png"))); // NOI18N
        imagen2.setToolTipText("¿Qué color es?");
        imagen2.setBorder(null);
        imagen2.setBorderPainted(false);
        imagen2.setContentAreaFilled(false);
        imagen2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imagen2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imagen2.setIconTextGap(-3);
        imagen2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        imagen2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        imagen2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imagen2ActionPerformed(evt);
            }
        });

        signo.setFont(new java.awt.Font("Arial", 0, 60)); // NOI18N
        signo.setText("=");
        signo.setToolTipText("");
        signo.setBorderPainted(false);
        signo.setContentAreaFilled(false);

        respuesta.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        respuesta.setForeground(new java.awt.Color(0, 0, 204));
        respuesta.setText("000");
        respuesta.setToolTipText("");
        respuesta.setOpaque(false);
        respuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                respuestaActionPerformed(evt);
            }
        });
        respuesta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                respuestaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                respuestaKeyTyped(evt);
            }
        });

        mensaje.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mensaje.setForeground(new java.awt.Color(255, 153, 0));
        mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mensaje.setText("Mensaje");
        mensaje.setToolTipText("");

        org.jdesktop.layout.GroupLayout jPanel6Layout = new org.jdesktop.layout.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .add(imagen1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(signo1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(imagen2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(signo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(respuesta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 101, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, mensaje, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel6Layout.createSequentialGroup()
                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel6Layout.createSequentialGroup()
                                .add(jPanel6Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, imagen2)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, imagen1))
                                .add(0, 0, Short.MAX_VALUE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, signo1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, signo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(jPanel6Layout.createSequentialGroup()
                        .add(36, 36, 36)
                        .add(respuesta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .add(mensaje, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Numeros/iconos/banner_rigth_suma.png"))); // NOI18N
        jLabel9.setToolTipText("");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        anterior2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/back_blue1.png"))); // NOI18N
        anterior2.setToolTipText("Anterior");
        anterior2.setBorder(null);
        anterior2.setBorderPainted(false);
        anterior2.setContentAreaFilled(false);
        anterior2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anterior2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        anterior2.setIconTextGap(-3);
        anterior2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/back_blue.png"))); // NOI18N
        anterior2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        anterior2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        anterior2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                anterior2MouseEntered(evt);
            }
        });
        anterior2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anterior2ActionPerformed(evt);
            }
        });

        siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/next_blue1.png"))); // NOI18N
        siguiente.setToolTipText("Siguiente");
        siguiente.setBorder(null);
        siguiente.setBorderPainted(false);
        siguiente.setContentAreaFilled(false);
        siguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        siguiente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        siguiente.setIconTextGap(-3);
        siguiente.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/next_blue.png"))); // NOI18N
        siguiente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        siguiente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        siguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                siguienteMouseEntered(evt);
            }
        });
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel7Layout = new org.jdesktop.layout.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(anterior2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(siguiente)
                .add(1, 1, 1))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel7Layout.createSequentialGroup()
                .add(jPanel7Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(anterior2)
                    .add(siguiente))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(10, 10, 10)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel9)
                    .add(jPanel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 1, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
            .add(layout.createSequentialGroup()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(jLabel9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void suma1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suma1MouseEntered
        suma1.setText("1+1=2");
    }//GEN-LAST:event_suma1MouseEntered

    private void suma1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suma1MouseExited
        suma1.setText("");
    }//GEN-LAST:event_suma1MouseExited

    private void suma2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suma2MouseEntered
        suma2.setText("Uno más uno son dos");
    }//GEN-LAST:event_suma2MouseEntered

    private void suma2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_suma2MouseExited
         suma2.setText("");
    }//GEN-LAST:event_suma2MouseExited

    private void anterior2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anterior2MouseEntered

    }//GEN-LAST:event_anterior2MouseEntered

    private void anterior2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anterior2ActionPerformed
        LaSuma1 suma_anterior=new LaSuma1();
        this.dispose();
        centrar(suma_anterior);
        clase.sonido("/Sonidos/water1.wav");
    }//GEN-LAST:event_anterior2ActionPerformed

    private void siguienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_siguienteMouseEntered

    }//GEN-LAST:event_siguienteMouseEntered

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        LaSuma2 suma_siguiente=new LaSuma2();
        this.dispose();
        centrar(suma_siguiente);
        clase.sonido("/Sonidos/water1.wav");
    }//GEN-LAST:event_siguienteActionPerformed

    private void imagen2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagen2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imagen2ActionPerformed

    private void imagen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imagen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imagen1ActionPerformed

    private void respuestaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_respuestaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_respuestaKeyPressed

    private void respuestaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_respuestaKeyTyped
        char c=evt.getKeyChar();
        int n=respuesta.getText().length();
        if(n>limite || (c<'0' || c>'9')){evt.consume();}
        if(c==KeyEvent.VK_ENTER){
            int index=(int)(Math.random()*totalmensajes);
            if(String.valueOf(suma).equals(respuesta.getText())){
                mensaje.setText(mensajeColor("estilo2", mensajeCorrecto[index]));
                suma(rango);
            }else{
                pError=pError+1;
                contador=contador+1;
                respuesta.setText("");
                respuesta.requestFocus();
                mensaje.setText(mensajeColor("estilo1", mensajeIncorrecto[index]));
            }
        }
    }//GEN-LAST:event_respuestaKeyTyped

    private void respuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_respuestaActionPerformed
        respuesta.selectAll();
    }//GEN-LAST:event_respuestaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anterior2;
    private javax.swing.JButton imagen1;
    private javax.swing.JButton imagen2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel mensaje;
    private javax.swing.JTextField respuesta;
    private javax.swing.JButton signo;
    private javax.swing.JButton signo1;
    private javax.swing.JButton siguiente;
    private javax.swing.JTextField suma1;
    private javax.swing.JTextField suma2;
    // End of variables declaration//GEN-END:variables
}
